---
title: "PM566 Final Project"
author: "Sabrina Zhong"
output: 
    html_document:
        toc: TRUE
        toc_float: TRUE
---

This is my PM566 Final Project website.

```{r setup, message=FALSE, echo=FALSE, warning=FALSE}
library(data.table)
library(tidyverse)
library(dplyr)
library(plotly)
library(DT)
library(knitr)

# Initialize code chunk options
opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  eval=TRUE,
  echo = TRUE,
  cache = FALSE,
  fig.width = 7, 
  fig.align = 'center',
  fig.asp = 0.618,
  out.width = "700px",
  class.source = "code-r")
```

```{css, echo = FALSE}
.code-r { /* Code block */
  font-size: 15px;
}

.code-r-small { /* Code block */
  font-size: 10px;
}
```


```{r load-data, echo = FALSE}
source(file = "suicide_data.R")
```
## Scatterplot of Suicide Rate vs. Sex
```{r p1, echo = FALSE}
p1_scatter
```
<br>

## Suicide Rate Trends from 2000-2019 {.tabset}

### Males
```{r p2_males, echo = FALSE}
p2_male_scatter
```
### Females
```{r p2_females, echo = FALSE}
p2_female_scatter
```
## {-}